---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-one-email
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-deployment
  template:
    metadata:
      labels:
        app: email-deployment
    spec:
      containers:
        - image: olvmky/p1-email-api
          imagePullPolicy: Always
          name: emailcontainer
          ports:
            - containerPort: 8088


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-app2
      port: 8079
      targetPort: 8070
  selector:
    app: email-deployment

