---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-email-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-deployment
  template:
    metadata:
      labels:
        app: email-deployment
    spec:
      containers:
        - image: olvmky/p1-email-api
          imagePullPolicy: Always
          name: project1-email-api
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: email-api-service
spec:
  selector:
    app: project1-email-api
  type: LoadBalancer
  ports:
    - name: http-app2
      port: 8088
      targetPort: 8088


